### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Moikapy** [fermentationist/wokeDyno#4]
Receives error whenever trying to npm i or yarn add project.

**Comment by fermentationist** [comment]
Sorry about that! I have not yet published this as an npm package, though I realize that the README prematurely contains directions for installation. I will publish it and update the README with new instructions as soon as I am able. If you found this repo because of the article I wrote on Hackernoon (https://hackernoon.com/how-to-prevent-your-free-heroku-dyno-from-sleeping-dggxo3bi2), there is an archived version of the code shown in the article here: https://github.com/fermentationist/wakeUpDyno .  And thanks for taking the time to read it!

**Comment by Moikapy** [comment]
Does the Current https://github.com/fermentationist/wokeDyno/blob/master/wokeDyno.js
work?

**Comment by fermentationist** [comment]
It should, now ; )

**Comment by fermentationist** [comment]
Although I haven’t finished implementing tests yet, I published it as an npm package that you may use: https://www.npmjs.com/package/woke-dyno

**Comment by Moikapy** [comment]
I'll try it out in my project.
